//TODO: Problem: auf goals muessen sowohl ueber jeweiligen Ort (also gGoal[MAX_LOCATIONS][MAX_GOALS]), als auch einzelne Goals, wenn z.B. nach 5 und 10 Minuten 3 und 5 Marines an einem Ort sein sollen...?

#ifndef _CORE_WARCRAFT3_HPP
#define _CORE_WARCRAFT3_HPP

#include "game.hpp"

class WARCRAFT3 : public GAME
{
	public:
		WARCRAFT3();
		~WARCRAFT3();

		void init();
		void initStringIdentifier();

                enum eResource
                {
                        GOLD,
                        WOOD
                };

                enum eAffectsResource
                {
                        AFFECTS_GOLD = 1,
                        AFFECTS_WOOD = 2,
                        AFFECTS_GOLD_AND_WOOD = 3, // 2 + 1
                        AFFECTS_GOLD_GLOBALLY = 129, // 128 + 1
                        AFFECTS_WOOD_GLOBALLY = 130, // 128 + 2
                        AFFECTS_GOLD_AND_WOOD_GLOBALLY = 131 // 128 + 2 + 1
                };

		enum eRace
		{
			HUMAN,
			ORC,
			ELVES,
			UNDEAD
		}; 

		enum eWarcraft3Units
		{
			NONE,
			
			GOLD_MINE,
			TREE,

			PEASANT,
			WOOD_PEASANT,
			PEASANT_FROM_WOOD_TO_GOLD,
			HUMAN_WAIT,
			
			MILITIA,
			FOOTMAN,
			RIFLEMAN,
			KNIGHT,
			PRIEST,
			SORCERESS,
			SPELL_BREAKER,

			GYROCEPTOR,
			MORTAR_TEAM,
			STEAM_TANK,
			GRYPHON_RIDER,
			DRAGONHAWK_RIDER,

			WATER_ELEMENTAL_LVL1,
			WATER_ELEMENTAL_LVL2,
			WATER_ELEMENTAL_LVL3,
			PHOENIX,

			PALADIN,
			ARCHMAGE,
			MOUNTAIN_KING,
			BLOOD_MAGE,

			FARM,
			TOWN_HALL,
			KEEP,
			CASTLE,
			HUMAN_BARRACKS,
			ALTAR_OF_KINGS,
			LUMBER_MILL,
			SCOUT_TOWER,
			BLACKSMITH,
			WORKSHOP,
			ARCANE_SANCTUM,
			GRYPHON_AVIARY,
			ARCANE_VAULT,
			GUARD_TOWER,
			CANNON_TOWER,
			ARCANE_TOWER,

			HUMAN_BACKPACK,
			DEFEND,
			LONG_RIFLES,
			ANIMAL_WAR_TRAINING,
			GYROCEPTOR_BOMBS,
			WAR_ENGINE,
			FLARE,
			FRAGMENTATION_SHARDS,
			STORM_HAMMERS,

			LUMBER_HARVESTING,
			MASONRY,
			MELEE_WEAPONS,
			MELEE_PLATING,
			RANGED_WEAPONS,
			LEATHER_ARMOR,
			PRIEST_TRAINING,
			SORCERESS_TRAINING,
			CONTROL_MAGIC,
			MAGIC_SENTINEL,

// mehrere upgrades!?
			R_HUMAN_BACKPACK,
			R_DEFEND,
			R_LONG_RIFLES,
			R_ANIMAL_WAR_TRAINING,
			R_GYROCEPTOR_BOMBS,
			R_WAR_ENGINE,
			R_FLARE,
			R_FRAGMENTATION_SHARDS,
			R_STORM_HAMMERS,

			R_LUMBER_HARVESTING,
			R_MASONRY,
			R_MELEE_WEAPONS,
			R_MELEE_PLATING,
			R_RANGED_WEAPONS,
			R_LEATHER_ARMOR,
			R_PRIEST_TRAINING,
			R_SORCERESS_TRAINING,
			R_CONTROL_MAGIC,
			R_MAGIC_SENTINEL,

			UNIT_TYPE_COUNT_HUMAN,
// TODO 'add peasant to building'

		//} // end eHumanUnits
		//
		//enum eOrcUnits
		//{

			PEON = 3,
			WOOD_PEON,
			PEON_FROM_WOOD_TO_GOLD,
			
			ORC_WAIT,


			GRUNT,
			HEADHUNTER,
			CATAPULT,
			RAIDER,
			TAUREN,
			SHAMAN,
			WITCH_DOCTOR,
			SPIRIT_WALKER,
			KODO_BEAST,
			WYVERN_RIDER,
			TROLL_BAT_RIDER,
			SPIRIT_WOLF_LVL1,
			DIRE_WOLF_LVL2,
			SHADOW_WOLF_LVL3,
			SERPENT_WARD,

			BLADEMASTER,
			FAR_SEER,
			TAUREN_CHIEFTAIN,
			SHADOW_HUNTER,

			BURROW,
			WAR_MILL,
			GREAT_HALL,
			STRONGHOLD,
			FORTRESS,
			ORC_BARRACKS,
			ALTAR_OF_STORMS,
			BESTIARY,
			SPIRIT_LODGE,
			TAUREN_TOTEM,
			VOODOO_LOUNGE,
			WATCH_TOWER,

			ORC_BACKPACK,
			PILLAGE,
			BERSERKER_STRENGTH,
			TROLL_REGENERATION,
			BERSERKER,
			BURNING_OIL,
			REINFORCED_DEFENSE,
			ENSNARE,
			WAR_DRUMS,
			ENVENOMED_SPEARS,
			LIQUID_FIRE,
			PULVERIZE,

			ORC_MELEE_WEAPONS,
			UNIT_ARMOR,
			ORC_RANGED_WEAPONS,
			SPIKED_BARRICADES,
			SHAMAN_TRAINING,
			WITCH_DOCTOR_TRAINING,
			SPIRIT_WALKER_TRAINING,


			R_ORC_BACKPACK,
			R_PILLAGE,
			R_BERSERKER_STRENGTH,
			R_TROLL_REGENERATION,
			R_BERSERKER,
			R_BURNING_OIL,
			R_REINFORCED_DEFENSE,
			R_ENSNARE,
			R_WAR_DRUMS,
			R_ENVENOMED_SPEARS,
			R_LIQUID_FIRE,
			R_PULVERIZE,

			R_ORC_MELEE_WEAPONS,
			R_UNIT_ARMOR,
			R_ORC_RANGED_WEAPONS,
			R_SPIKED_BARRICADES,
			R_SHAMAN_TRAINING,
			R_WITCH_DOCTOR_TRAINING,
			R_SPIRIT_WALKER_TRAINING,

			UNIT_TYPE_COUNT_ORC,
		//}
		//
		//enum eElvesUnits
		//{
			WISP = 3,
			WOOD_WISP,
			WISP_FROM_WOOD_TO_GOLD,
	
			ELVES_WAIT,
			BREAK_UP_BUILDING,

			ARCHER,
			HUNTRESS,
			BALLISTA,
			DRYAD,
			DRUID_OF_THE_CLAW,
			MOUNTAIN_GIANT,
			HIPPOGRYPH,
			DRUID_OF_THE_THALON,
			FAERIE_DRAGON,
			CHIMAERA,
			TREANT,
			SPIRIT_OF_VENGEANCE,
			VENGEANCE,

			DEMON_HUNTER,
			KEEPER_OF_THE_GROVE,
			PRIESTESS_OF_THE_MOON,
			WARDEN,

			ANCIENT_OF_WAR,
			ANCIENT_OF_LORE,
			ANCIENT_OF_WIND,
			ANCIENT_PROTECTOR,
			TREE_OF_LIFE,
			TREE_OF_AGES,
			TREE_OF_ETERNITY,

			ANCIENT_OF_WONDERS,
			MOON_WELL,
			ALTAR_OF_ELDERS,
			HUNTERS_HALL,
			CHIMAERA_ROOST,

			ELVES_BACKPACK,
			IMPROVED_BOWS,
			MARKSMANSHIP,
			SENTINEL,
			MOON_GLAIVE,
			IMPALING_BOLT,
			ULTRAVISION,
			WELL_SPRING,
			NATURES_BLESSING,
			ABOLISH_MAGIC,
			ENCHANTED_BEARS,
			HARDENED_SKIN,
			RESISTANT_SKIN,
			HIPPOGRYPH_TRAINING,
			ENCHANTED_CROWS,
			CORROSIVE_BREATH,
			STRENGTH_OF_THE_MOON,
			MOON_ARMOR,
			STRENGTH_OF_THE_WILD,
			REINFORCED_HIDE,
			DRUID_OF_THE_CLAW_TRAINING,
			DRUID_OF_THE_THALON_TRAINING,

			R_ELVES_BACKPACK,
			R_IMPROVED_BOWS,
			R_MARKSMANSHIP,
			R_SENTINEL,
			R_MOON_GLAIVE,
			R_IMPALING_BOLT,
			R_ULTRAVISION,
			R_WELL_SPRING,
			R_NATURES_BLESSING,
			R_ABOLISH_MAGIC,
			R_ENCHANTED_BEARS,
			R_HARDENED_SKIN,
			R_RESISTANT_SKIN,
			R_HIPPOGRYPH_TRAINING,
			R_ENCHANTED_CROWS,
			R_CORROSIVE_BREATH,
			R_STRENGTH_OF_THE_MOON,
			R_MOON_ARMOR,
			R_STRENGTH_OF_THE_WILD,
			R_REINFORCED_HIDE,
			R_DRUID_OF_THE_CLAW_TRAINING,
			R_DRUID_OF_THE_THALON_TRAINING,

			
			UNIT_TYPE_COUNT_ELVES,
		//}
		//
		//enum eUndeadUnits
		//{



			ACOLYTE = 3,

			UNSUMMON_BUILDING,
			UNDEAD_WAIT,

			GHOUL,
			CRYPT_FIEND,
			GARGOYLE,
			ABOMINATION,
			MEAT_WAGON,
			NECROMANCER,
			BANSHEE,
			FROST_WYRM,
			SHADE,
			SKELETON_WARRIOR,
			SKELETAL_MAGE,
			INFERNAL,
			CARRION_BEETLE_LVL1,
			CARRION_BEETLE_LVL2,
			CARRION_BEETLE_LVL3,
			OBSIDIAN_STATUE,

			DEATH_KNIGHT,
			DREAD_LORD,
			LICH,
			CRYPT_LORD,

			HAUNTED_GOLD_MINE,
			NECROPOLIS,
			HALLS_OF_THE_DEAD,
			BLACK_CITADEL,
			CRYPT,
			ZIGGURAT,
			ALTAR_OF_DARKNESS,
			GRAVEYARD,
			SLAUGHTERHOUSE,
			TEMPLE_OF_THE_DAMNED,
			SACRIFICIAL_PIT,
			BONEYARD,
			TOMB_OF_RELICS,
			NERUBIAN_TOWER,
			SPIRIT_TOWER,

			UNDEAD_BACKPACK,
			CANNIBALIZE,
			GHOUL_FRENZY,
			WEB,
			BURROW_UNDEAD,
			STONE_FORM,
			DISEASE_CLOUD,
			EXHUME_CORPSES,
			DESTROYER,
			SKELETAL_LONGEVITY,
			SKELETAL_MASTERY,
			FREEZING_BREATH,
			UNHOLY_STRENGTH,
			UNHOLY_ARMOR,
			CREATURE_ATTACK,
			CREATURE_CARAPACE,
			NECROMANCER_TRAINING,
			BANSHEE_TRAINING,

			R_UNDEAD_BACKPACK,
			R_CANNIBALIZE,
			R_GHOUL_FRENZY,
			R_WEB,
			R_BURROW_UNDEAD,
			R_STONE_FORM,
			R_DISEASE_CLOUD,
			R_EXHUME_CORPSES,
			R_DESTROYER,
			R_SKELETAL_LONGEVITY,
			R_SKELETAL_MASTERY,
			R_FREEZING_BREATH,
			R_UNHOLY_STRENGTH,
			R_UNHOLY_ARMOR,
			R_CREATURE_ATTACK,
			R_CREATURE_CARAPACE,
			R_NECROMANCER_TRAINING,
			R_BANSHEE_TRAINING,

			UNIT_TYPE_COUNT_UNDEAD
				
		}; // end eUndeadUnits
                
		enum eBroodwarStrings
                {
                        NULL_STRING,
                        HUMAN_STRING,
                        ORC_STRING,
                        ELVES_STRING,
			UNDEAD_STRING,

                        GOLD_STRING = 10,
                        WOOD_STRING,
// force window:
                        UNIT_TYPE_0_STRING = 20,
                        UNIT_TYPE_1_STRING,
                        UNIT_TYPE_2_STRING,
                        UNIT_TYPE_3_STRING,
                        UNIT_TYPE_4_STRING,
                        UNIT_TYPE_5_STRING,
                        UNIT_TYPE_6_STRING,
                        UNIT_TYPE_7_STRING,
                        UNIT_TYPE_8_STRING,
                        UNIT_TYPE_9_STRING,
                        UNIT_TYPE_10_STRING,

                        GAME_SPEED_SLOWEST_STRING = 40,
                        GAME_SPEED_SLOWER_STRING, // 9
                        GAME_SPEED_SLOW_STRING, // 12
                        GAME_SPEED_NORMAL_STRING, // 15
                        GAME_SPEED_FAST_STRING, // 18
                        GAME_SPEED_FASTER_STRING, // 21
                        GAME_SPEED_FASTEST_STRING, // 24

                        MAX_WARCRAFT3_STRINGS
                };
		enum eGameSpeedFrames
		{
			GAME_SPEED_SLOWEST,
			GAME_SPEED_SLOWER,
			GAME_SPEED_SLOW,
			GAME_SPEED_NORMAL,
			GAME_SPEED_FAST,
			GAME_SPEED_FASTER,
			GAME_SPEED_FASTEST,
			MAX_GAME_SPEED
		};

	private:
};


#endif // _CORE_WARCRAFT3_HPP




