#ifndef _GUI_HELP_WINDOW_HPP
#define _GUI_HELP_WINDOW_HPP

#include "../ui/window.hpp"
#include "../ui/longtext.hpp"

enum eHelpChapter {
	INDEX_CHAPTER = 0,
	
	INTRODUCTION_MAIN_CHAPTER = 100,
	INTRODUCTION_CHAPTER = 110,
	INTRODUCTION_QUICKSTART_CHAPTER = 120,
	INTRODUCTION_OVERVIEW_CHAPTER = 130,
	INTRODUCTION_USE_CHAPTER = 140,
	INTRODUCTION_LIMITS_CHAPTER = 150,
	INTRODUCTION_PROBLEMS_CHAPTER = 160,

	DESCRIPTION_MAIN_CHAPTER = 200,
	DESCRIPTION_SCORE_WINDOW_CHAPTER = 210,
	DESCRIPTION_GOAL_WINDOW_CHAPTER = 220,
	DESCRIPTION_FORCE_WINDOW_CHAPTER = 230,
	DESCRIPTION_BODIAGRAM_WINDOW_CHAPTER = 240,
	DESCRIPTION_BOGRAPH_WINDOW_CHAPTER = 250,
	DESCRIPTION_BUILD_ORDER_WINDOW_CHAPTER = 260,

	RESULTS_MAIN_CHAPTER = 300,
	RESULTS_TIME_AND_NUMBERS_CHAPTER = 310,
	RESULTS_OUTPUT_CHAPTER = 320,
	RESULTS_DATABASE_CHAPTER = 330,
	RESULTS_INGAME_CHAPTER = 340,

	MECHANICS_MAIN_CHAPTER = 400,
	MECHANICS_ORDER_CHAPTER = 410,
	MECHANICS_MULTIPLAYER_CHAPTER = 420,
	MECHANICS_FINETUNE_CHAPTER = 430,
	MECHANICS_SIMULATION_CHAPTER = 440,

	INTERACTIVE_MAIN_CHAPTER = 500,
	INTERACTIVE_EDITING_CHAPTER = 510,
	INTERACTIVE_PLAYING_CHAPTER = 520,
	INTERACTIVE_TOURNAMENTS_CHAPTER = 530,
	INTERACTIVE_WHATTOLEARN_CHAPTER = 540,

	CORE_MAIN_CHAPTER = 600,
	CORE_ALGORITHM_CHAPTER = 610,
	CORE_BUILDORDER_CHAPTER = 620,
	CORE_SCALABILITY_CHAPTER = 630,
	CORE_COMPARISON_CHAPTER = 640,
	CORE_PROBLEMS_GAS_CHAPTER = 650,

	COMMUNICATION_MAIN_CHAPTER = 700,
	COMMUNICATION_CLAWSOFTWARE_CHAPTER = 710,
	COMMUNICATION_ABOUT_CHAPTER = 730,

	DEVELOPMENT_MAIN_CHAPTER = 800,
	DEVELOPMENT_HISTORY_CHAPTER = 810,
	DEVELOPMENT_NOTIMPLEMENTED_CHAPTER = 820,
	DEVELOPMENT_TODO_CHAPTER = 830,
	DEVELOPMENT_CURRENT_CHAPTER = 840,
	DEVELOPMENT_FUTURE_CHAPTER = 850,

	PHILOSOHPY_MAIN_CHAPTER = 900,
	PHILOSOPHY_EVOLUTION_CHAPTER = 910,
	PHILOSOPHY_GOD_CHAPTER = 920,
	PHILOSOPHY_REALITY_CHAPTER = 930
};

class HelpWindow : public UI_Window
{
	public:
		HelpWindow(UI_Window* parent_window);
		~HelpWindow();
		void process();
		void draw(DC* dc) const;
		void reloadOriginalSize();
	private:
		eHelpChapter helpChapter; // ~~
		UI_LongText* text;
		UI_Button* indexButton;
		UI_Button* backButton;
		std::list<eHelpChapter> lastChapter;
};

#endif

